import React from 'react'
import '../Styles/Style.scss'

const Written = () => {
  return (
    <>
      <div className="w-100 bg-white shadow px-5 pt-3 my-2">
        <h4>Top Stories:Brand Directory</h4>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda beatae facere illo dolorum porro fugit, repudiandae praesentium cum officiis. Sapiente itaque odit omnis explicabo magni quisquam neque atque nihil blanditiis.
        Deserunt, error. Magni accusantium, aliquid doloribus maxime ut quas illo repellendus aspernatur debitis ipsam. Doloribus accusantium esse voluptas, rerum similique ex placeat ea molestiae autem fugiat, voluptatum eius quis ducimus.
        Exercitationem rerum similique omnis, sapiente tempora ipsa commodi possimus voluptates accusamus laborum, consequatur accusantium quidem! Non molestiae, sit numquam doloremque qui cum quod optio quas aliquid inventore, ipsam, corporis praesentium.
        Dolore iste, officia expedita animi dolores, quo amet possimus officiis culpa explicabo deleniti. Dolore assumenda blanditiis numquam iure minima pariatur voluptatem consectetur provident exercitationem maiores itaque, accusantium ex, optio veritatis?
        Mollitia doloribus eveniet laborum! Qui repellat fugit optio, sit natus reprehenderit cumque explicabo aliquam, ducimus at culpa praesentium dolore! Velit perferendis officiis, eaque cupiditate cum voluptas blanditiis laboriosam saepe nulla.
        Explicabo laudantium velit omnis odit, fugiat esse, nam quidem non error veritatis assumenda quia nisi consectetur soluta nobis amet minima. Optio natus, beatae sint dolore vel necessitatibus consectetur commodi quaerat.
        Natus vero doloremque, eaque repellat quaerat aliquid iusto qui laudantium quis dolores enim temporibus laboriosam consectetur officiis dolorum minus consequatur nihil molestias hic dolorem perspiciatis ullam obcaecati aliquam? Dolorum, quae!
        Labore eius illum facilis at delectus deleniti ducimus dolores non fuga reprehenderit quia molestias error eum vero, similique velit pariatur iusto doloremque quam sunt sequi soluta esse aliquam! Dignissimos, consequatur.
        Aliquid facilis, sed provident modi odit id quisquam? Suscipit commodi odio possimus natus facilis ipsam repellat nam placeat, optio cum velit magni qui, recusandae, repudiandae beatae totam dicta dolore molestiae!
        Sequi ipsam ut voluptatem ad inventore sed pariatur veritatis quae amet consequatur, similique sapiente at aperiam nemo deleniti fugiat eveniet ullam tempore reiciendis tenetur perferendis, incidunt velit natus. Provident, earum.
        Repellendus ad dignissimos libero? In illum repudiandae dicta cumque maxime perspiciatis nisi veniam, nostrum eos ipsa architecto ea ab vero molestias pariatur commodi quo quae autem delectus nemo? Necessitatibus, exercitationem.
        Deleniti nam iure esse placeat aspernatur cum qui quaerat quam ad, sint dolores eligendi culpa ratione id vitae recusandae. Repudiandae velit impedit nesciunt placeat autem nemo laudantium nam suscipit praesentium!
        Nam reiciendis est ipsum autem harum incidunt quas consectetur dicta inventore, unde obcaecati sapiente atque assumenda, exercitationem maiores nulla, mollitia fuga hic repudiandae odit. Vel quod et itaque voluptate doloremque.
        Officia sint delectus dolore consequatur labore, cumque amet aut dolores possimus. Nulla facilis laborum in debitis, expedita dolorem repellat atque, repellendus ducimus hic iusto nostrum aperiam accusantium illo voluptate incidunt?
        Minima libero aut, consequatur officiis earum architecto. Earum, voluptatem eligendi fuga libero ex ipsam deleniti laborum itaque mollitia tempora debitis at consequatur exercitationem similique sequi ea. Eum sed corrupti officiis?
        Sit sint quo molestias, illum beatae eaque natus reiciendis optio aspernatur incidunt eius numquam esse amet at molestiae soluta in autem atque cupiditate ex qui temporibus voluptatum? Quisquam, tempora officia!
        Et optio sit, deserunt beatae maiores quos amet ea ducimus illum officiis omnis vel quia earum porro doloribus corrupti, perferendis libero in voluptates vero error, veritatis ratione minus! Accusantium, ad.
        Velit magnam esse quas? Perspiciatis distinctio, nulla id sit laborum quisquam ipsam quaerat culpa ad adipisci sint provident tempora, itaque enim laboriosam! Corrupti eos cupiditate voluptatum. Numquam temporibus provident dolor.
        Eveniet et vel tempora velit pariatur. Quod deleniti voluptate esse laborum minus. Nam eligendi natus ex aliquid necessitatibus quae, libero dolorem vel, nihil quasi modi ipsum nesciunt numquam delectus! Molestiae!
        Quaerat molestiae velit similique numquam dolorum amet ad doloremque soluta laboriosam temporibus distinctio minus nemo, dignissimos quo quod ab exercitationem ipsum, officia vitae porro at quam maiores. Dolor, quidem obcaecati.
        Itaque nisi autem officiis. Blanditiis provident asperiores, soluta dolores unde eum officia incidunt eligendi amet veritatis praesentium? Perspiciatis reiciendis ducimus error dolor, hic excepturi? Voluptatum explicabo dicta ad possimus expedita.
        Explicabo qui vitae alias vero aliquam deserunt neque, eos veritatis tempore corporis quas doloremque eius! Nemo omnis itaque aperiam. Dolorum non provident culpa, sit quas explicabo molestiae eligendi consequuntur quos.
        Itaque, sapiente rem optio iure dolor alias perferendis quisquam temporibus in libero officia quasi asperiores. Voluptatum voluptas dolores nesciunt iure nihil, ea aut, consequatur sint est adipisci libero, modi doloremque.
        Nulla, aut placeat fugiat repellendus quasi, libero aliquid quas culpa dolore ut fugit repellat eos eum reprehenderit. Temporibus soluta dignissimos quas non distinctio amet modi quae, mollitia cum exercitationem! Dicta.
        Et quibusdam nostrum aspernatur architecto incidunt est quis ea quos quas rerum, blanditiis officiis esse non, aperiam vel. Odio facere vero dolor non laborum. Aut porro doloremque corporis debitis aliquam.
        Minima impedit consectetur voluptatem quam laudantium sed inventore quod distinctio a aut, doloribus placeat id quia provident beatae odio commodi in rem facere earum tempore alias. Veritatis, eligendi magnam? Omnis.
        Id deleniti autem cupiditate odit voluptate ratione repellendus consequatur voluptatem quae, fuga delectus dolorem voluptas ab? Asperiores, accusamus nostrum nobis facilis incidunt magnam vero dolor illo nihil quod quia! Sed?
        Aliquid sint quis deserunt minima consectetur quidem itaque ea veritatis et iure nihil quia quos possimus natus eaque, a eius, doloribus ab nobis inventore ullam? Magnam alias repudiandae asperiores corrupti?
        Doloribus deleniti eligendi suscipit facilis molestias laboriosam soluta cupiditate est eos, at natus repellat ducimus asperiores beatae harum totam alias facere dolores dolor expedita officia maxime voluptatum pariatur. Magni, magnam.
        Dolor, mollitia sapiente! Cum, numquam porro voluptas ratione, maxime, placeat unde autem libero quidem repudiandae delectus ut culpa officiis error quas! Possimus rerum ad dolorem ea molestias repudiandae laborum neque!
        Reiciendis in omnis ratione pariatur vel possimus nihil? Beatae, repellat optio harum voluptatum rem doloremque qui eveniet. Saepe velit totam rerum, blanditiis, delectus laborum numquam distinctio ea fugit possimus assumenda.
        Incidunt iure assumenda officia dolor consectetur reiciendis atque adipisci molestiae accusamus, voluptatem officiis facere reprehenderit. Recusandae ullam, atque laboriosam accusamus quae voluptate? Rem eligendi animi obcaecati ex quae aspernatur at.
        Consectetur cum ea qui praesentium voluptatem numquam? Nemo qui numquam deserunt iure vitae. Possimus minus sapiente obcaecati recusandae non reiciendis dolore repellat quo inventore totam similique, aspernatur at sit provident?
        Veniam commodi eaque architecto rem et expedita minima deserunt maxime totam facilis aperiam asperiores nemo, quam nam delectus eligendi sapiente veritatis vel natus sunt illo nisi quidem. Neque, consectetur ex!
        Ad nesciunt est ipsum explicabo ex nobis ratione, temporibus, debitis fugiat tempore reiciendis quis minus quae libero sed velit. Perferendis consequatur consectetur ut corporis laborum architecto nobis! Inventore, libero laborum!
        Fugit exercitationem vero earum eaque, natus dolorem dolores dignissimos mollitia aut harum facilis eveniet. Aspernatur ea hic tenetur sunt odio amet voluptatem. Assumenda amet quasi, eius aliquid aspernatur fugit autem.
        Impedit dolorum distinctio eius recusandae animi atque maxime fugit repellendus. Ratione harum pariatur, accusamus eligendi quos recusandae itaque. Dolorum maxime quae itaque. Sapiente expedita, blanditiis nesciunt illo rem quaerat cumque?
        Dolor quam adipisci odit nihil explicabo necessitatibus hic. Nihil perspiciatis rem molestias rerum deserunt perferendis aspernatur nesciunt fuga provident nisi corporis, numquam ab distinctio reprehenderit velit, dolorem consequuntur sint voluptates!
        Est, ipsum! Fuga voluptas, et officiis voluptate aliquid quisquam harum voluptatum animi quibusdam nulla. Ipsam facilis illum amet fugiat ab nesciunt debitis ducimus culpa sint magnam delectus, perferendis cumque saepe?
        Illo, dicta quidem dignissimos ratione earum molestias nam aperiam quae porro numquam, beatae ipsam debitis cumque, libero eveniet facere. Velit provident sint, quis ipsum magni iusto voluptatem eius fuga officiis.
        Voluptate magnam eligendi ipsa, tenetur omnis officia laudantium rerum facere ullam architecto eveniet error, voluptates, facilis magni? Esse cumque molestiae similique, corporis asperiores, aliquam accusamus veritatis quibusdam reprehenderit voluptate eaque.
        Omnis est modi odio inventore aperiam, quaerat pariatur a quisquam labore eveniet! Facere quasi, atque similique doloribus porro ea consectetur nulla. Explicabo voluptates blanditiis maiores accusantium, aliquid itaque fugiat doloribus?
        Deserunt sequi ad natus animi voluptates assumenda iste nulla, itaque eveniet nesciunt vel est ratione vero molestias quos doloribus incidunt at ab totam possimus? Deserunt, quo reiciendis! Laudantium, aut blanditiis?
        Earum nulla officia nihil, delectus quaerat consequatur molestias animi corporis, temporibus, ad totam odit. Eligendi recusandae cum perspiciatis officiis distinctio fugiat numquam quas provident, harum, totam velit ducimus molestiae hic.
        Ut, aliquam rerum iste reiciendis totam officiis, vitae quod odit recusandae aspernatur quae similique eos delectus quos nemo. Repellat doloremque at rerum est, quos a neque sequi similique! At, ipsum?
        Blanditiis mollitia incidunt vitae ab quis soluta molestiae eos laboriosam culpa aut autem ad distinctio ipsum aliquam sint facere voluptas quos reprehenderit, sunt quisquam tempora, corporis aspernatur. Quisquam, corrupti quis.
        Quis ab quisquam in neque nemo maxime itaque voluptate reprehenderit, veritatis praesentium id dicta aut ullam alias dolore voluptatem eum eius? Iste, nostrum nam magni iure odio temporibus id autem.
        Assumenda sequi sit eos itaque? Neque reprehenderit repudiandae odit ex laudantium magnam, autem temporibus consequatur deleniti eum earum modi unde nesciunt? Mollitia similique ad quis, reiciendis molestiae iste eaque quidem?
        Illum dignissimos ratione reiciendis in atque placeat velit eaque, quia, optio repellendus eveniet fugit tempore, reprehenderit vitae alias consequatur consequuntur? Architecto asperiores maiores doloremque minima minus? Aliquam doloremque asperiores corrupti?
        Asperiores cumque nostrum, qui accusantium adipisci sint tempore possimus aspernatur, repudiandae fugit ea accusamus dolor, odit modi recusandae nam harum debitis praesentium quo dolores! Veniam, iure! Tempora cupiditate nam ut!
        Incidunt distinctio fugiat deleniti ex animi voluptate beatae fuga? Aliquid sit eius quae non. Nisi, repellendus aut ab quia nobis ex incidunt perferendis assumenda voluptate tempora, voluptates saepe. Perferendis, at.
        Error, optio dolor, expedita deserunt tempora commodi recusandae sapiente obcaecati dolorem maiores fugit ex nam aliquid nesciunt, omnis iusto possimus eligendi sequi non natus maxime unde adipisci. Fugit, totam doloremque.
        Eveniet tempore expedita nobis ullam ea maiores consectetur minus rem laudantium, fugiat dignissimos perspiciatis quaerat quibusdam harum libero sapiente ut est laborum vel! Commodi sapiente quos totam minima voluptas animi.
        Molestias animi sed aut saepe placeat amet rerum accusamus voluptatem. Sit cum dolorem fugiat nisi pariatur porro accusantium reiciendis eius. Praesentium minus tempora sed reprehenderit nihil aut nostrum libero corporis.
        In ipsa voluptates fuga ratione velit, aspernatur id odit impedit sunt quia incidunt dicta doloribus est magni itaque animi! Rerum id cupiditate sint dolores qui, magnam facere inventore reprehenderit aliquid?
        Iusto inventore at dolore necessitatibus, veniam optio beatae earum odit voluptatum saepe nobis a, fugit ipsum quae repellat est eius, quo quibusdam laborum? Eos autem excepturi iure delectus obcaecati fuga.
        Numquam illum eos optio reiciendis totam quo odio obcaecati voluptate placeat rem. Odit aliquam ratione deleniti nihil distinctio! Laudantium, ea? Placeat voluptates dolore quaerat maxime excepturi! Impedit labore debitis quam.
        Voluptas perspiciatis modi id ratione voluptate vel cumque. In corrupti ipsa velit voluptatum impedit ratione nisi error exercitationem sit odio officia ducimus, eius debitis adipisci molestias soluta? Aliquam, soluta ex!
        Laborum, facere excepturi! Quam rerum, aliquam vel labore eum cum ab repellat assumenda molestias aspernatur amet quasi nostrum rem? Aliquam tenetur repellat molestias sit eius iste asperiores, amet repellendus beatae.
        Optio porro magnam nam rerum fuga est dolorem vero, architecto veritatis, ab quas reprehenderit, tempore saepe alias reiciendis! Earum quo vero maiores voluptatem! Id esse, omnis earum ipsam fugit in.
        Sit distinctio, ex culpa repellendus iusto magni deleniti cum magnam doloribus tenetur ratione neque iure, delectus quidem, praesentium placeat ullam harum excepturi eius animi optio aspernatur? Quod distinctio facere nulla!
        Sit placeat quas libero magni repellat amet dolorem ipsum. Facere quo minima, velit eum ab nemo corrupti maiores sed aliquam harum vitae dolorum accusantium sit nisi distinctio cupiditate a voluptatibus.
        Incidunt cum iusto architecto quaerat cupiditate debitis repudiandae provident pariatur amet maiores voluptas dolorem est corrupti, dignissimos inventore. Nulla dolore architecto provident autem harum dignissimos deserunt fuga expedita rem corrupti.
        Nesciunt aliquam odio quas sunt porro consequatur? Facere consectetur, esse, illo sint quisquam magni sit sequi optio dolor vel nesciunt itaque, dolorem iure. Harum ullam earum ipsam quam minima porro.
        Non quisquam neque voluptatibus rem ab deserunt dolor asperiores delectus quia ullam, fugiat laboriosam consequuntur, natus nobis maxime, rerum nihil nesciunt corporis odio sapiente repudiandae cum reprehenderit. Eius, necessitatibus in?
        Numquam consequatur nemo debitis, dolorum accusantium a! Nesciunt eum reprehenderit placeat adipisci illo, distinctio debitis rerum. Itaque vel nobis ad natus tempora, labore nesciunt molestias dolores dolore odit magnam consequatur!
        Totam asperiores et minima veniam! Excepturi labore recusandae, sed error voluptates repudiandae fugiat quia mollitia tenetur omnis quae veniam, architecto laborum nulla debitis eius ducimus magnam reiciendis, pariatur dolore facere.
        At sapiente eos veniam voluptatum, in distinctio officiis labore assumenda natus nisi delectus aliquid adipisci consectetur, molestias fugiat. Exercitationem perferendis possimus excepturi quis repellendus voluptatem recusandae distinctio enim ea corrupti?
        Similique dignissimos delectus sit sapiente, maiores in reprehenderit voluptates ipsa qui expedita sunt, ab provident est facere quaerat. Voluptatum, veniam est! Odit vitae, esse iure molestiae deserunt modi ipsam delectus.
        Cupiditate ullam eveniet dicta, maxime eos odit distinctio consequatur, rem sequi vel voluptatibus? Aspernatur eaque ut placeat. Et, deserunt quo. Sit et facere modi ducimus ad ipsam numquam soluta hic!
        Veritatis hic qui ab natus ut, dolor debitis laudantium, quisquam maiores facere et sequi alias itaque. Nobis veniam velit officiis consequuntur tempora dolores nesciunt consequatur, impedit autem et quam ipsam.
        Ex, quas fuga reprehenderit consequuntur adipisci tempora explicabo totam. Exercitationem, id. Ratione delectus architecto earum at illum. Praesentium sit at, quos voluptates, illo tenetur deleniti cupiditate alias dolor ullam sed?
        Nesciunt veniam blanditiis obcaecati expedita in provident aperiam omnis possimus optio adipisci accusantium alias officiis nihil a aspernatur cupiditate eum dolore, distinctio asperiores pariatur laborum nisi maiores ex. Tempora, non.
        Laborum ratione ipsa id ad totam atque! Consectetur, a officiis. Repellendus est aliquam rem! Laborum ipsum aliquid maxime assumenda quia, quis libero porro veritatis suscipit cum quibusdam perferendis mollitia fugiat!
        Modi, eius? Voluptate dignissimos unde animi voluptas corporis velit omnis voluptates voluptatibus voluptatum aperiam at modi nam, similique ad minima, adipisci eius facilis ut sint eveniet quo repellat est distinctio.
        Quaerat perferendis dignissimos impedit quo commodi et, nam nostrum sed aliquam rerum at quisquam voluptates natus! Fugit maxime, ducimus, sapiente earum modi similique accusantium corrupti harum excepturi adipisci fugiat quia.
        Natus quia facilis repellendus. Rem, doloremque amet beatae perferendis, vitae illum assumenda dicta cumque molestiae nulla officiis nesciunt hic. Exercitationem minima aliquam neque totam culpa officia architecto tenetur modi odio.
        Totam voluptas nemo dolorum repellat sed molestiae molestias reiciendis enim modi, harum voluptatibus quae dolor tempora itaque aperiam magnam exercitationem asperiores deleniti iure vitae ipsa! Tempora nesciunt ipsum in aliquid.
        Officia at ipsum omnis a tenetur repellendus officiis ab vero temporibus minus consectetur, esse dignissimos veniam distinctio, aliquam cum dolores aliquid nesciunt ipsam sequi ut neque enim. Laborum, incidunt rerum.
        Minus alias sapiente similique quibusdam dolor dolorem provident voluptas porro voluptate quam! Voluptas, provident? Praesentium dolorum quos facilis dolore aliquam quisquam voluptas, ipsa magnam, omnis nobis eius nam placeat exercitationem!
        Incidunt quis at, totam rem soluta tempora obcaecati eveniet tempore libero nulla saepe aut nisi modi tenetur deleniti quas expedita assumenda veritatis atque optio harum ipsam veniam quibusdam. Ratione, dignissimos?
        Dolorum quas perferendis dolore minus asperiores provident voluptates. Esse ut sint quod doloremque voluptatem dolores eveniet, illo totam maxime inventore, tempore modi quaerat minus, sapiente dolorem error aliquam doloribus odio.
        Explicabo, eaque? Aspernatur tenetur tempore maxime voluptatem, nulla voluptatum, placeat pariatur harum suscipit excepturi nisi a deserunt natus magni earum quam autem rerum omnis inventore. Facere ad dolorem facilis adipisci!
        Sapiente soluta numquam et! Itaque a necessitatibus laboriosam maiores eligendi delectus quasi autem quas quidem, labore ipsa facere magni enim, officia sapiente totam! Sunt inventore sapiente esse porro ab eos.
        Quisquam similique, ut dicta, nesciunt vitae ratione iure repellendus id ullam sed consequatur nulla placeat quod eius itaque odit aspernatur, dignissimos sunt ipsum dolore aliquam dolores nemo saepe! Commodi, esse!
        Explicabo mollitia maxime at incidunt, repudiandae odio porro omnis cum perspiciatis ducimus nulla quis, expedita saepe reiciendis non fugit ipsum libero possimus voluptatum alias soluta quod a. Ad, repudiandae nemo?
        Voluptate qui facere, laborum alias dolores illum excepturi ad, reprehenderit amet recusandae eum vel, nisi deleniti harum! Nihil iure porro eaque, deserunt a, assumenda quaerat incidunt, repellat consectetur quis dolorum!
        Consequuntur veritatis dolor reprehenderit quia nostrum repellendus eum perferendis. Neque ipsum itaque autem vel minima aspernatur, minus maiores necessitatibus, tenetur sit iure consequatur iste inventore nihil incidunt quibusdam animi fugiat.
        Inventore, asperiores quo ducimus eius optio blanditiis fuga adipisci maxime tempore cumque velit suscipit, dolore nulla ipsam, consectetur assumenda nisi similique natus perspiciatis temporibus odio aspernatur sint accusantium qui. Ducimus.
        Saepe necessitatibus possimus illo suscipit quo, tenetur corporis harum laboriosam pariatur cum inventore blanditiis quam amet id unde assumenda quasi doloribus porro impedit nesciunt rerum quia! Ea aliquid odio eligendi.
        Recusandae ipsam unde aperiam maxime sed quos explicabo, ut voluptatem sequi vero quisquam rem, quia repudiandae deserunt. Saepe sed, odit aspernatur, aut labore autem tenetur error vitae nobis, odio inventore!
        Minus expedita laudantium, quibusdam possimus porro veritatis tempora ipsam vero ipsa sapiente iusto accusamus. Nihil, facilis ullam, blanditiis alias placeat officiis cupiditate tempora quas, nobis illo consectetur ab. Architecto, molestias!
        Ab minima temporibus iste quos accusantium, veritatis iure nam earum ipsa, inventore dolorem atque in. Fugit modi, omnis assumenda architecto et perspiciatis neque excepturi? Atque consectetur aliquam libero ea laboriosam!
        Officia, adipisci quos. Libero animi necessitatibus quo earum ut velit perferendis facere iure ad exercitationem accusantium et recusandae id facilis minima, obcaecati atque ex veritatis voluptate! Hic suscipit sint minus?
        Architecto pariatur magnam, voluptatem ea tenetur, itaque hic aliquid, iste tempore aperiam sunt quos recusandae beatae voluptatibus non a expedita qui nobis in. Tempore ratione dolorem aliquid consectetur nulla provident.
        Velit necessitatibus voluptatem odio quas officiis iste odit deleniti molestiae. Voluptas enim laborum iure impedit at deserunt unde sapiente in. Aliquam excepturi blanditiis sunt! Possimus deserunt aliquid voluptates expedita cupiditate?
        Dolores alias necessitatibus magnam quos neque? Tenetur minima libero voluptates sunt doloremque nulla illum autem dolorum blanditiis similique reprehenderit reiciendis, praesentium rem incidunt voluptas quaerat officiis, culpa assumenda. Ullam, eius!
        Dolor facere quas ipsa repellendus quod dicta quia! Sunt eum laborum excepturi natus. Maxime, quaerat? Quos laudantium rem dolore, dolorem nulla quo animi laboriosam vero nam aspernatur aperiam sit error.
        Eligendi sint enim et velit quidem magni voluptates autem dolor, aut ullam minus error repellat reprehenderit at praesentium. Placeat corrupti illum ipsum animi voluptatum, quidem quibusdam. Mollitia ex nemo doloribus.
        Provident soluta aliquid sunt aspernatur tempora eos inventore autem iure corporis! Dolores esse ut a explicabo inventore asperiores quasi ad natus odio. Inventore magni illum hic obcaecati doloribus rerum et?
      </div>
    </>
  )
}

export default Written
